name: Syncer

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install
      run: |
        echo "install chart-syncer"
        GOBIN=/usr/local/bin go install github.com/appscode-charts/chart-syncer@v0.0.2
        echo
        echo "install helm 3"
        pushd /usr/local/bin && sudo curl -fsSLO https://github.com/x-helm/helm/releases/latest/download/helm && sudo chmod +x helm && popd

    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync
      run: |
        chart-syncer -r ghcr.io/appscode-charts -a aws-ebs-csi-driver -u https://kubernetes-sigs.github.io/aws-ebs-csi-driver -c aws-ebs-csi-driver
        chart-syncer -r ghcr.io/appscode-charts -a cert-manager -u https://charts.jetstack.io -c cert-manager
        chart-syncer -r ghcr.io/appscode-charts -a cluster-autoscaler -u https://kubernetes.github.io/autoscaler -c cluster-autoscaler
        chart-syncer -r ghcr.io/appscode-charts -a crossplane -u https://charts.crossplane.io/stable -c crossplane
        chart-syncer -r ghcr.io/appscode-charts -a falcosecurity -u https://falcosecurity.github.io/charts -c falco
        chart-syncer -r ghcr.io/appscode-charts -a fluxcd-community -u https://fluxcd-community.github.io/helm-charts -c flux2
        chart-syncer -r ghcr.io/appscode-charts -a fluxcd-community -u https://fluxcd-community.github.io/helm-charts -c flux2-multi-tenancy
        chart-syncer -r ghcr.io/appscode-charts -a fluxcd-community -u https://fluxcd-community.github.io/helm-charts -c flux2-notification
        chart-syncer -r ghcr.io/appscode-charts -a fluxcd-community -u https://fluxcd-community.github.io/helm-charts -c flux2-sync
        chart-syncer -r ghcr.io/appscode-charts -a gatekeeper -u https://open-policy-agent.github.io/gatekeeper/charts -c gatekeeper
        chart-syncer -r ghcr.io/appscode-charts -a kedacore -u https://kedacore.github.io/charts -c keda
        chart-syncer -r ghcr.io/appscode-charts -a kedacore -u https://kedacore.github.io/charts -c keda-add-ons-http
        chart-syncer -r ghcr.io/appscode-charts -a nats -u https://nats-io.github.io/k8s/helm/charts -c nats
        chart-syncer -r ghcr.io/appscode-charts -a prometheus-community -u https://prometheus-community.github.io/helm-charts -c kube-prometheus-stack
        chart-syncer -r ghcr.io/appscode-charts -a stakater -u https://stakater.github.io/stakater-charts -c reloader
