name: Syncer

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install
      run: |
        GOBIN=/usr/local/bin go install github.com/appscode-charts/chart-syncer@latest

    - name: Sync
      run: |
        chart-syncer -h
